# Generated by Django 3.2.7 on 2021-11-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('hockey', 'Hockey'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('football', 'Football'), ('soccer', 'Soccer')], default='hockey', max_length=50),
        ),
    ]
